[target.wasm32-wasi]
rustflags = [
  "-Z", "wasi-exec-model=reactor",
  "-lc++",
  "-lc++abi",
  # "-lc-printscan-long-double",
  # "-lc-printscan-no-floating-point",
  "-lc",
  "-lcrypt",
  "-ldl",
  "-lm",
  "-lpthread",
  "-lresolv",
  "-lrt",
  "-lutil",
  "-lwasi-emulated-mman",
  "-lwasi-emulated-signal",
  "-lxnet"
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-lstdc++"
]
[target.x86_64-apple-darwin]
rustflags = [
#  "-lstdc++",
#  "-lc++abi", 
  "-lc++"
]
linker = "rust-lld"

[target.aarch64-apple-darwin]
rustflags = [
#  "-lstdc++",
#  "-lc++abi",
  "-lc++"
]
linker = "rust-lld"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-lucrtd"]
#rustflags = ["-C", "target-feature=+crt-static"]
#rustflags= ["target-feature=+crt-static"]
#rustflags = ["-lntdll"]
#rustflags=["-lucrt"]

[build]
#target = "wasm32-wasi"

